name: Release Contribution Notifier

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Commenter
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: chriskarlin/github-release-commenter@author-template
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            @{pr_author}: Your PR/Issue `{pr_title}` is part of today's Human Essentials production release: {release_link}. 
            Thank you very much for your contribution!
